 const messages = [
    {"value":"May you be gifted with life’s biggest joys and never-ending bliss. After all, you yourself are a gift to earth, so you deserve the best!"},
    {"value":"Count not the candles…see the lights they give. Count not the years, but the life you live. Wishing you a wonderful time ahead!" }, 
    {"value":"Forget the past; look forward to the future, for the best things are yet to come!"},
    {"value":"You are only young once, but you can be immature for a lifetime!"},
    {"value":"Cheers to you for another trip around the sun!"},
    {"value":"Wishing you a beautiful day with good health and happiness forever."},
    {"value":"To quote Shakespeare: ‘Party thine ass off!’"},
    {"value":"Don’t forget to smile awkwardly as everyone sings you happy birthday today!"},
    {"value":"Birthdays are nature’s way of telling us to eat more cake!"},
    {"value":"On your birthday I’m going to share the secret to staying young: lie about your age."},
    {"value":"Work hard. Play hard. Eat lots of cake. That’s a good motto for your birthday and for life."},
    {"value":"Hope you get birthday presents in the dozens!"},
    {"value":"May you have all the love your heart can hold, all the happiness a day can bring, and all the blessings a life can unfold."},
    {"value":"Be happy! Today is the day you were brought into this world to be a blessing and inspiration to the people around you! You are a wonderful person! May you be given more birthdays to fulfill all of your dreams!"},
    {"value":"Forget about the past, you can’t change it. Forget about the future, you can’t predict it. And forget about the present, I didn’t get you one. Happy birthday!"},
    {"value":"As you get older three things happen. The first is your memory goes, and I can’t remember the other two. Happy birthday!"},
    {"value":"When the little kids ask how old you are at your party, you should go ahead and tell them. While they’re distracted trying to count that high, you can steal a bite of their cake! Happy birthday!"},
    {"value":"Sending you smiles for every moment of your special day…Have a wonderful time and a very happy birthday!"},
    {"value":"Sending you a birthday wish wrapped with all my love. Have a very happy birthday!"},
    {"value":"A simple celebration, a gathering of friends; here wishing you great happiness and a joy that never ends. Happy birthday!"},
    {"value":"Hope your birthday is just like you…totally freaking awesome."},
    {"value":"I hope that today, at your party, you dance and others sing as you celebrate with joy your best birthday."},
    {"value":"It’s always a treat to wish happy birthday to someone so sweet."},
    {"value":"Hey you! It’s your birthday! Cake! Candles! Drinks! Presents! More food! Can you tell I’m excited?"},
    {"value":"Happy birthday to my forever young friend!"},
    {"value":"Birthdays only come once a year, and your friendship only comes once a lifetime."},
    {"value":"You deserve all the cake, happiness, and love today. Happy birthday!"},
    {"value":"Thank you for being the brightest person I know. Hope to see you shine for years on! Happy birthday!"},
    {"value":"May your birthday be sprinkled with fun and laughter. Have a great day!"},
    {"value":"Happy Birthday! I hope you have a great day today, and the year ahead is full of many blessings"},
    {"value":"Wishing you a very happy birthday! May all your dreams come true."},
    {"value":"Congratulations on your birthday! Sending you our love and good wishes."},
    {"value":"Many happy returns to you on your birthday! We hope you have a wonderful day full of friends, family, and cake!"},
    {"value":"On the bright side, at least you don't have to share your birthday cake with anyone else this year!"},
    {"value":"I can't wait to be less than 6 feet away from you! Happy birthday!"},
    {"value":"Sending lots of love and a big virus-free hug on your birthday. I miss you enormously, and I can't wait to take you out to party properly once lockdown is over!!"},
    {"value":"Keep Calm and Stay Safe... and have a very Happy Birthday!"},
    {"value":"Those aren't gray hairs that you see. They're strands of birthday glitter growing out of your head."},
    {"value":"You're not getting older... just more distinguished! Happy Birthday."},
    {"value":"I spent 3 hours searching the internet for the perfect birthday message for you and then I gave up. Happy Birthday."},
    {"value":" To many more years of friendship and fun. Happy, happy birthday!"},
    {"value":" I couldn’t imagine a better friend. Thanks for all the memories! Happy birthday!"},
    {"value":"I’m so glad to be able to celebrate this day with a special friend. Happy birthday!"},
    {"value":"Happy birthday! May your day be filled with lots of love and happiness."},
    {"value":"You’re older than yesterday, but younger than tomorrow! Happy birthday!!"},

]

export default messages;

