import React,{useState} from "react";
import Head from "next/head";
import styles from "../styles/Name.module.css";
import { useRouter } from "next/router";
import ConfettiGenerator from "confetti-js";
import messages from "../utils/birthdayWishes.js";

const title = (name) => {

    const wish = 'Happy Birthday ' + name + "!"
    const letters = []
    
    for (let i = 0; i < wish.length; i++) {
        const letter = wish.charAt(i)

        if(i > 14)
            letters.push(<span key={i} style={{"--i": i + 1}} className={styles.span}>{letter}</span>)
        else
            letters.push(<span key={i} style={{"--i": i + 1}}>{letter}</span>)
    }

    return (
        <h1 className={styles.title} style={{"--wish-length": wish.length}}>
            {letters.map((letter) => letter)}
        </h1>
    )
}

const Wish = () => {

  const router = useRouter();
  const { name } = router.query;
  const [color, setColor] = useState([]);
  const [linkTitle, setLinkTitle] = useState([]);
  // In future work (button visible will be depends on routes).
  const [buttonVisible, setButtonVisible] = useState([]);

  React.useEffect(() => {
    const confettiSettings = {
      target: "canvas",
      start_from_edge: true,
    };
    setLinkTitle("Copy Link");
    setColor("#0070f3");
    setButtonVisible(true);
    const confetti = new ConfettiGenerator(confettiSettings);
    confetti.render();

    return () => confetti.clear();
  }, []);
  // function for randomly picking the message from messages array
  const randomNumber = (min, max) => {
    return Math.floor(Math.random() * (max - min)) + min;
  };
  const copyToClipboard = (e) => {
    // This is just personal preference.
    e.preventDefault();
    navigator.clipboard.writeText(window.location.href);

    setColor("#10B981");
    setLinkTitle("Link Copied");
    setButtonVisible(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Happy Birthday {name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <canvas className={styles.canvas} id="canvas"></canvas>

      <main className={styles.animate}>
        <div className={styles.main}>
          <h1 className={styles.title}>
              {title(name)}
          </h1>
        </div>
        <p className={styles.desc}>
          {messages[randomNumber(0, messages.length)].value}
        </p>
              <div>
                  {buttonVisible && linkTitle === "Copy Link" ? <button style={{ backgroundColor: color }} onClick={copyToClipboard} className={styles.buttonCopy} >
                      {linkTitle}
                  </button> : ''}
                  {buttonVisible && linkTitle === "Link Copied" ? <button style={{ backgroundColor: color }} onClick={copyToClipboard} className={styles.buttonCopied} >
                      {linkTitle}
                  </button> : ''}
                  <button onClick={() => router.push("/")} className={styles.button}>
                      &larr; Create a wish
                  </button>
              </div>
      </main>
    </div>
  );
};

export default Wish;
