import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Router from 'next/router'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create a Birthday Wish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.main}>
          <h1 className={styles.title}>
            Create a <span className={styles.span}>Birthday</span> Wish
          </h1>
        </div>
        <div>
          <form className={styles.form} onSubmit={input}>
            <input name="go" id="input" className={styles.input} placeholder="Enter name of the person" />
            <button className={styles.button} type="submit">Go!</button>
            <br/>
            <br/>
            <input name="desc" id="desc" className={styles.desc} placeholder="Enter custom description (optional)" />
          </form>
          <p className={styles.desc}>
            Crafted by <a className={styles.span} href="https://github.com/gouravkhunger" target="_blank" rel="noreferrer">Gourav</a>.
          </p>
        </div>
      </main>
    </div>
  )
}

const input = event => {
  event.preventDefault() // don't redirect the page
  // where we'll add our form logic
  const value = event.target.querySelector('#input').value
  if (!value) {
    alert("Please enter a name!")
    return
  }
  const desc = event.target.querySelector('#desc').value
  if(!desc){
    Router.push(value)
  }
  else{
    Router.push(value+"?msg="+window.btoa(desc))
  }  
}
