import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Router from 'next/router'
import { useEffect, useState } from 'react';

export default function Home() {
  const [color,setColor] = useState('#0070f3');

  const handleThemeChange = event =>{
    setColor(event.target.value);
  }
  
  useEffect(()=>{
    changeTheme(color);
  },[color]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create a Birthday Wish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.main}>
          <h1 className={styles.title}>
            Create a <span className={styles.span}>Birthday</span> Wish
          </h1>
        </div>
        {/* Theme Color  */}
        <div>
          <form className={styles.theme} id='theme-input' onChange={handleThemeChange}>
        
              <input type='radio' id='blue' name='theme' value='#0070f3'/>
              <input type='radio' id='green' name='theme' value='#10B981'/>
              <input type='radio' id='violet' name='theme' value='#8B5CF6'/>
              <input type='radio' id='yellow' name='theme' value='#FBBF24'/>
              <input type='radio' id='red' name='theme' value='#E11D48'/>
         
          </form>
        </div>
        <div>
          <form className={styles.form} onSubmit={input}>
            <input name="go" className={styles.input} placeholder="Enter name of the person" />
            <button className={styles.button} type="submit">Go!</button>
          </form>
          <p className={styles.desc}>
            Crafted by <a className={styles.span} href="https://github.com/gouravkhunger" target="_blank" rel="noreferrer">Gourav</a>.
          </p>
        </div>
      </main>
    </div>
  )
}

const input = event => {
  event.preventDefault() // don't redirect the page
  // where we'll add our form logic
  const value = event.target.querySelector('input').value
  if (!value) {
    alert("Please enter a name!")
    return
  }
  Router.push(value)
}

const changeTheme = color => {
  let root = document.documentElement;
  root.style.setProperty('--color',color);
}